### ISSUE TITLE
Service Export Attributes

### ISSUE THREAD

**Issue by set321go** [ops4j/peaberry#82]
I'm trying to export a service with an attribute with multiple values. I gathered the basics from your old docs https://code.google.com/p/peaberry/wiki/UserGuide but I can't seem to get it to work. 

I have tried

```
names("letter=A;letter=B;letter=C")
names("letter=A;B;C")
names("letter=A,letter=B,letter=C")
names("letter=A,B,C")
names("letter=A B C")
```

The problem is I can't find any documentation on how to define an array/list/set in LDAP syntax, although there is much on how to make multi valued queries.

**Comment by mcculls** [comment]
The LDAP parser used in `names` only parses single-value attributes, but you can add multi-value attributes as follows:

```
import static java.util.Collections.singletonMap;
import static org.ops4j.peaberry.util.Attributes.*;

// ...

Map<String, ?> attributes = union(
  names( "CN=John Doe,OU=Sales,DC=Acme,DC=COM" ),
  singletonMap( "letter", new String[] { "A", "B", "C" } )
);
```

**Comment by set321go** [comment]
Thanks
